[package]
name = "kitchensync"
version = "0.1.0"
authors = ["Stephen Lee <sphen.lee@gmail.com>"]

[dependencies]
clap = "2.26.2"
walkdir = "0.1.8"
url = "1.2.0"
sha1 = "0.2.0"
log = "0.3.8"
colored = "1.5"
atty = "0.2.2"
rusoto_core = "0.28.0"
rusoto_s3 = "0.28.0"
rayon = "0.8.2"
indicatif = "0.7.0"

[[bin]]
name = "kitchensync"
