[package]
name = "kitchensync"
version = "0.1.0"
authors = ["Stephen Lee <sphen.lee@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
async-trait = "0.1"
aws-sdk-s3-transfer-manager = "0.1.1"
aws-config = { version= "1.8.12", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.8"
clap = "4.5"
clout = "0.2"
colored = "3"
futures = "0.3"
indicatif = "0.18"
log = "0.4"
rayon = "1.5"
serde = "1.0"
sha1 = "0.10"
thiserror = "2"
tokio = { version = "1", features = ["fs", "tracing"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"]}
toml = "0.9.8"
url = "2"
utime = "0.3"
walkdir = "2"

[[bin]]
name = "kitchensync"
