[package]
name = "kitchensync"
version = "0.1.0"
authors = ["Stephen Lee <sphen.lee@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.26.2"
walkdir = "2"
url = "2"
sha1 = "0.2.0"
log = "0.4.0-rc.1"
env_logger = "0.7"
colored = "1.5"
atty = "0.2.2"
rusoto_core = "*"
rusoto_s3 = "*"
indicatif = "0.15"
utime = "0.3"
tokio = { version = "0.2", features = ["io-util"] }
clout = "0.2"

[[bin]]
name = "kitchensync"
